### ISSUE TITLE
à archiver ?

### ISSUE THREAD

**Issue by Seluj78** [AFPy/python-nantes#16]
cc qqun de nantes ?

**Comment by alexgarel** [comment]
@arthurlogilab ?

**Comment by arthurlogilab** [comment]
J'aimerais garder. À moins que archiver veut juste dire "mettre en sommeil le dépot git et conserver le site http://nantes.afpy.org/"

**Comment by Seluj78** [comment]
Yes c'est ca que ca veux dire :)

**Comment by JulienPalard** [comment]
Oui, tant que le site est en prod, je peux avoir besoin de faire des commits.
